/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as JuanRouteImport } from './routes/$juan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsStudentsRouteImport } from './routes/posts/$students'
import { Route as PostsIdRouteImport } from './routes/posts/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const JuanRoute = JuanRouteImport.update({
  id: '/$juan',
  path: '/$juan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsStudentsRoute = PostsStudentsRouteImport.update({
  id: '/posts/$students',
  path: '/posts/$students',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$juan': typeof JuanRoute
  '/about': typeof AboutRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/$students': typeof PostsStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$juan': typeof JuanRoute
  '/about': typeof AboutRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/$students': typeof PostsStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$juan': typeof JuanRoute
  '/about': typeof AboutRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/$students': typeof PostsStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$juan' | '/about' | '/posts/$id' | '/posts/$students'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$juan' | '/about' | '/posts/$id' | '/posts/$students'
  id: '__root__' | '/' | '/$juan' | '/about' | '/posts/$id' | '/posts/$students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JuanRoute: typeof JuanRoute
  AboutRoute: typeof AboutRoute
  PostsIdRoute: typeof PostsIdRoute
  PostsStudentsRoute: typeof PostsStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$juan': {
      id: '/$juan'
      path: '/$juan'
      fullPath: '/$juan'
      preLoaderRoute: typeof JuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$students': {
      id: '/posts/$students'
      path: '/posts/$students'
      fullPath: '/posts/$students'
      preLoaderRoute: typeof PostsStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JuanRoute: JuanRoute,
  AboutRoute: AboutRoute,
  PostsIdRoute: PostsIdRoute,
  PostsStudentsRoute: PostsStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
